### ISSUE TITLE
Verhalten bei Serverfehlern oder Timeouts

### ISSUE THREAD

**Issue by lukasl66** [AOEpeople/meals-android#21]
Was passiert in der Webview wenn eine URL nicht aufgerufen werden kann? Bitte überprüfen und Gedanken um UX machen.

**Comment by TobiasUhmann** [comment]
The Progress bar indicates loading correctly now (Shows during any page load, not just first page load).

If the Server doesn't respond because it's down or if the user is not connected to the Internet an error message is shown. 

TODO:
- allow Manual Refreshing on swipe down
- automatically try to refresh if the last loading failed

**Comment by TobiasUhmann** [comment]
Automatic refreshing has not been implemented. Manual refreshing, however, is possible by swiping down now.
